version: "2.1"

volumes:
  shinobi:
  videos:
  mariadb:

services:
  shinobi:
    build: .
    privileged: true
    ports:
      - "80:8080/tcp"
    volumes:
      - shinobi:/config
      - videos:/opt/shinobi/videos
    links:
      - mariadb

  mariadb:
    image: mariadb:10-bionic
    volumes:
      - mariadb:/var/lib/mysql
